### ISSUE TITLE
pyportal_simpletest - TFT in use

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_PyPortal#48]
the pyportal_simpletest.py fails - with CP 5.0 at least
 ```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-alpha.0-45-gd99d3bd47 on 2019-07-28; Adafruit PyPortal with samd51j20
>>> 
>>> 
>>> import pyportal_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyportal_simpletest.py", line 10, in <module>
  File "adafruit_pyportal.py", line 172, in __init__
ValueError: TFT_BACKLIGHT in use
>>> 
```

**Comment by jerryneedell** [comment]
update -- this fails as well with CP 4.0.2 and CP4.1.0

**Comment by jerryneedell** [comment]
this was recently changed (5 days ago) - it used to try/except for the ValueError
https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/blame/master/adafruit_pyportal.py#L170
